spring.application.name=hirelink-backend

spring.datasource.url=jdbc:mysql://localhost:3306/hirelink_db
spring.datasource.username=satya_sree
spring.datasource.password=Satya@1111

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=satyasree.2005prathipati@gmail.com
spring.mail.password=pmwiiivbnfllffeb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8081